version: "3.3"

services:
  db:
    image: mongo:4.2-bionic
    expose:
      - "27017"
    volumes:
      - /var/db:/data/db
  cache:
    image: redis:6.2.6
    expose:
      - "6379"
    volumes:
      - /var/redis:/data
  api:
    image: api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache