version: "3.3"

services:
  db:
    logging:
      driver: none
    image: mongo:4.2-bionic
    expose:
      - "27017"
    volumes:
      - /var/db:/data/db
  cache:
    logging:
      driver: none
    image: redis:6.2.6
    expose:
      - "6379"
    volumes:
      - /var/redis:/data
  api:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: api-test
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache