# Build stage
FROM golang:1.17-buster AS build

WORKDIR /build

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY src/ ./src
COPY main.go ./
COPY test.env ./

ENTRYPOINT [ "go", "test", "-v", "/build/src/..." ]